-- MySQL Script generated by MySQL Workbench
-- Sun Apr  6 14:22:52 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BibliotecaDigital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BibliotecaDigital` ;
USE `BibliotecaDigital` ;

-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`C_CAMPANA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`C_CAMPANA` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`C_CAMPANA` (
  `ID_C_CAMP` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_CAMP` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_C_CAMP`),
  CONSTRAINT `FK_RELATIONSHIP_21`
    FOREIGN KEY (`ID_CAMP`)
    REFERENCES `BibliotecaDigital`.`CAMPANA` (`ID_CAMP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene los catalogos de campaña';

CREATE INDEX `FK_RELATIONSHIP_21` ON `BibliotecaDigital`.`C_CAMPANA` (`ID_CAMP` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_desborde`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_desborde` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_desborde` (
  `id_desborde` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_desborde`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_tipo_usuario` (
  `ID_TIPO_USR` INT(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_TIPO` VARCHAR(20) NOT NULL,
  `DESCRIPCION_TIPO` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_USR`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene el catalogo de tipos de Usuario';


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`usuario` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`usuario` (
  `ID_USR` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_TIPO_USR` INT(11) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  `NOMBRE_USR` VARCHAR(30) NOT NULL,
  `APELLIDO_PATERNO_USR` VARCHAR(30) NOT NULL,
  `APELLIDO_MATERNO_USR` VARCHAR(30) NOT NULL,
  `EMAIL_USR` VARCHAR(50) NOT NULL,
  `ESTATUS_USR` INT(11) NOT NULL,
  PRIMARY KEY (`ID_USR`),
  CONSTRAINT `FK_RELATIONSHIP_2`
    FOREIGN KEY (`ID_TIPO_USR`)
    REFERENCES `BibliotecaDigital`.`c_tipo_usuario` (`ID_TIPO_USR`))
ENGINE = InnoDB
AUTO_INCREMENT = 91
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene la informacion de Usuarios';

CREATE INDEX `FK_RELATIONSHIP_2` ON `BibliotecaDigital`.`usuario` (`ID_TIPO_USR` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_integracion_crm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_integracion_crm` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_integracion_crm` (
  `ID_INT_CRM` INT(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(20) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL DEFAULT NULL,
  `ESTATUS` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID_INT_CRM`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene el catalogo de integraciones CRM';


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`campana`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`campana` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`campana` (
  `ID_CAMP` INT(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_CAMP` VARCHAR(100) NOT NULL,
  `TERM_LLAMADA` TINYINT(1) NOT NULL,
  `ID_USR` INT(11) NOT NULL,
  `MARCACION_SALIDA` TINYINT(4) NOT NULL,
  `tipo_camp` TINYINT(4) NOT NULL,
  `id_int_crm` INT(11) NULL DEFAULT NULL,
  `id_desborde` INT(11) NULL DEFAULT NULL,
  `num_extension` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CAMP`),
  CONSTRAINT `FK_RELATIONSHIP`
    FOREIGN KEY (`id_desborde`)
    REFERENCES `BibliotecaDigital`.`c_desborde` (`id_desborde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RELATIONSHIP_55`
    FOREIGN KEY (`ID_USR`)
    REFERENCES `BibliotecaDigital`.`usuario` (`ID_USR`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RELATIONSHIP_60`
    FOREIGN KEY (`id_int_crm`)
    REFERENCES `BibliotecaDigital`.`c_integracion_crm` (`ID_INT_CRM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 164
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla campaña';

CREATE INDEX `FK_RELATIONSHIP_55` ON `BibliotecaDigital`.`campana` (`ID_USR` ASC);

CREATE INDEX `FK_RELATIONSHIP_60` ON `BibliotecaDigital`.`campana` (`id_int_crm` ASC);

CREATE INDEX `FK_RELATIONSHIP` ON `BibliotecaDigital`.`campana` (`id_desborde` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`agenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`agenda` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`agenda` (
  `ID_AGENDA` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_CAMP` INT(11) NOT NULL,
  PRIMARY KEY (`ID_AGENDA`),
  CONSTRAINT `FK_RELATIONSHIP_8`
    FOREIGN KEY (`ID_CAMP`)
    REFERENCES `BibliotecaDigital`.`campana` (`ID_CAMP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_8` ON `BibliotecaDigital`.`agenda` (`ID_CAMP` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`campana_outbound`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`campana_outbound` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`campana_outbound` (
  `ID_CAMP` INT(11) NOT NULL,
  `MAX_TONOS` INT(11) NOT NULL,
  `PRIORIDAD_AG_CALLE` TINYINT(1) NOT NULL,
  `ID_CAMP_OUT` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID_CAMP_OUT`),
  CONSTRAINT `FK_RELATIONSHIP_9`
    FOREIGN KEY (`ID_CAMP`)
    REFERENCES `BibliotecaDigital`.`campana` (`ID_CAMP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_9` ON `BibliotecaDigital`.`campana_outbound` (`ID_CAMP` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`campana_inbound`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`campana_inbound` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`campana_inbound` (
  `ID_CAMP` INT(11) NOT NULL,
  `MAX_CICLOS` INT(11) NOT NULL,
  `ID_CAMP_IN` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID_CAMP_IN`),
  CONSTRAINT `FK_RELATIONSHIP_13`
    FOREIGN KEY (`ID_CAMP`)
    REFERENCES `BibliotecaDigital`.`campana` (`ID_CAMP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_13` ON `BibliotecaDigital`.`campana_inbound` (`ID_CAMP` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`alarmas_externas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`alarmas_externas` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`alarmas_externas` (
  `NUM_MAX_MSGFILA` INT(11) NOT NULL,
  `NUM_MAX_LLAMFILA` INT(11) NOT NULL,
  `TMP_MAX_FILA` INT(11) NOT NULL,
  `ID_ALARMA_EXTERNA` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_CAMP_OUT` INT(11) NULL DEFAULT NULL,
  `ID_CAMP_IN` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ALARMA_EXTERNA`),
  CONSTRAINT `FK_RELATIONSHIP_11`
    FOREIGN KEY (`ID_CAMP_OUT`)
    REFERENCES `BibliotecaDigital`.`campana_outbound` (`ID_CAMP_OUT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RELATIONSHIP_15`
    FOREIGN KEY (`ID_CAMP_IN`)
    REFERENCES `BibliotecaDigital`.`campana_inbound` (`ID_CAMP_IN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene los atributos de alarmas externas';

CREATE INDEX `FK_RELATIONSHIP_11` ON `BibliotecaDigital`.`alarmas_externas` (`ID_CAMP_OUT` ASC);

CREATE INDEX `FK_RELATIONSHIP_15` ON `BibliotecaDigital`.`alarmas_externas` (`ID_CAMP_IN` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`alarmas_internas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`alarmas_internas` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`alarmas_internas` (
  `MIN_AGENTES` INT(11) NOT NULL,
  `LIM_TMP_LLAMADA` INT(11) NOT NULL,
  `TMP_MAX_PAUSA` INT(11) NOT NULL,
  `CAMB_EST_AGENTE` INT(11) NOT NULL,
  `ID_ALARMA_INTERNA` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_CAMP_IN` INT(11) NULL DEFAULT NULL,
  `ID_CAMP_OUT` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ALARMA_INTERNA`),
  CONSTRAINT `FK_RELATIONSHIP_12`
    FOREIGN KEY (`ID_CAMP_OUT`)
    REFERENCES `BibliotecaDigital`.`campana_outbound` (`ID_CAMP_OUT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RELATIONSHIP_14`
    FOREIGN KEY (`ID_CAMP_IN`)
    REFERENCES `BibliotecaDigital`.`campana_inbound` (`ID_CAMP_IN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_12` ON `BibliotecaDigital`.`alarmas_internas` (`ID_CAMP_OUT` ASC);

CREATE INDEX `FK_RELATIONSHIP_14` ON `BibliotecaDigital`.`alarmas_internas` (`ID_CAMP_IN` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`bloqueo_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`bloqueo_login` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`bloqueo_login` (
  `idbloqueo_login` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usr` INT(11) NULL DEFAULT NULL,
  `intentos` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idbloqueo_login`),
  CONSTRAINT `fk_usuario_bloqueo`
    FOREIGN KEY (`id_usr`)
    REFERENCES `BibliotecaDigital`.`usuario` (`ID_USR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_usuario_bloqueo` ON `BibliotecaDigital`.`bloqueo_login` (`id_usr` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_sistema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_sistema` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_sistema` (
  `ID_C_SISTEMA` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID_C_SISTEMA`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene los catalogos de Sistema';


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_actividades_paus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_actividades_paus` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_actividades_paus` (
  `ID_ACT_PAUSA` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_C_SISTEMA` INT(11) NULL DEFAULT NULL,
  `ACTIVIDAD_PAUSA` VARCHAR(15) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ACT_PAUSA`),
  CONSTRAINT `FK_RELATIONSHIP_37`
    FOREIGN KEY (`ID_C_SISTEMA`)
    REFERENCES `BibliotecaDigital`.`c_sistema` (`ID_C_SISTEMA`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene el catalogo de actividades en pausa';

CREATE INDEX `FK_RELATIONSHIP_37` ON `BibliotecaDigital`.`c_actividades_paus` (`ID_C_SISTEMA` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_campana_integracion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_campana_integracion` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_campana_integracion` (
  `id_camp` INT(11) NOT NULL,
  `id_int_crm` INT(11) NOT NULL,
  `estatus` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id_camp`, `id_int_crm`),
  CONSTRAINT `FK_RELATIONSHIP_44`
    FOREIGN KEY (`id_int_crm`)
    REFERENCES `BibliotecaDigital`.`c_integracion_crm` (`ID_INT_CRM`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RELATIONSHIP_59`
    FOREIGN KEY (`id_camp`)
    REFERENCES `BibliotecaDigital`.`campana` (`ID_CAMP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_44` ON `BibliotecaDigital`.`c_campana_integracion` (`id_int_crm` ASC);

CREATE INDEX `FK_RELATIONSHIP_59` ON `BibliotecaDigital`.`c_campana_integracion` (`id_camp` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_resultados_inbou`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_resultados_inbou` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_resultados_inbou` (
  `ID_RES_IN` INT(11) NOT NULL AUTO_INCREMENT,
  `RESULTADO` VARCHAR(50) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_RES_IN`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_campana_resultadosin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_campana_resultadosin` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_campana_resultadosin` (
  `id_camp` INT(11) NOT NULL,
  `id_res_in` INT(11) NOT NULL,
  `estatus` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id_camp`, `id_res_in`),
  CONSTRAINT `FK_RELATIONSHIP_61`
    FOREIGN KEY (`id_res_in`)
    REFERENCES `BibliotecaDigital`.`c_resultados_inbou` (`ID_RES_IN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RELATIONSHIP_62`
    FOREIGN KEY (`id_camp`)
    REFERENCES `BibliotecaDigital`.`campana` (`ID_CAMP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_61` ON `BibliotecaDigital`.`c_campana_resultadosin` (`id_res_in` ASC);

CREATE INDEX `FK_RELATIONSHIP_62` ON `BibliotecaDigital`.`c_campana_resultadosin` (`id_camp` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_resultados_outbo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_resultados_outbo` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_resultados_outbo` (
  `ID_RES_OUT` INT(11) NOT NULL AUTO_INCREMENT,
  `RESULTADO` VARCHAR(50) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_RES_OUT`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene el catalogo de Resultados Outbound';


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_campana_resultadosout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_campana_resultadosout` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_campana_resultadosout` (
  `id_camp` INT(11) NOT NULL,
  `id_res_out` INT(11) NOT NULL,
  `estatus` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id_camp`, `id_res_out`),
  CONSTRAINT `FK_RELATIONSHIP_63`
    FOREIGN KEY (`id_res_out`)
    REFERENCES `BibliotecaDigital`.`c_resultados_outbo` (`ID_RES_OUT`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RELATIONSHIP_64`
    FOREIGN KEY (`id_camp`)
    REFERENCES `BibliotecaDigital`.`campana` (`ID_CAMP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_63` ON `BibliotecaDigital`.`c_campana_resultadosout` (`id_res_out` ASC);

CREATE INDEX `FK_RELATIONSHIP_64` ON `BibliotecaDigital`.`c_campana_resultadosout` (`id_camp` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_estado_agente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_estado_agente` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_estado_agente` (
  `ID_ESTADO` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_C_SISTEMA` INT(11) NULL DEFAULT NULL,
  `NOMBRE_EDO` VARCHAR(10) NOT NULL,
  `DESCRIPCION_EDO` TEXT NULL DEFAULT NULL,
  `COLOR` VARCHAR(15) NULL DEFAULT NULL,
  `DESCRIPCION_COLOR` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ESTADO`),
  CONSTRAINT `FK_RELATIONSHIP_45`
    FOREIGN KEY (`ID_C_SISTEMA`)
    REFERENCES `BibliotecaDigital`.`c_sistema` (`ID_C_SISTEMA`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene los catalogos de estao de agente ';

CREATE INDEX `FK_RELATIONSHIP_45` ON `BibliotecaDigital`.`c_estado_agente` (`ID_C_SISTEMA` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_gpo_atn_inbound`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_gpo_atn_inbound` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_gpo_atn_inbound` (
  `ID_GPO_ATN_IN` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_C_SISTEMA` INT(11) NULL DEFAULT NULL,
  `GRUPO_ATENCION` VARCHAR(30) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_GPO_ATN_IN`),
  CONSTRAINT `FK_RELATIONSHIP_36`
    FOREIGN KEY (`ID_C_SISTEMA`)
    REFERENCES `BibliotecaDigital`.`c_sistema` (`ID_C_SISTEMA`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene el catalogo de Grupos de Atencion';

CREATE INDEX `FK_RELATIONSHIP_36` ON `BibliotecaDigital`.`c_gpo_atn_inbound` (`ID_C_SISTEMA` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_perfiles_agenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_perfiles_agenda` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_perfiles_agenda` (
  `ID_PERF_AGENDA` INT(11) NOT NULL AUTO_INCREMENT,
  `PERFIL` VARCHAR(15) NOT NULL,
  `DESCRIPCCION` VARCHAR(100) NULL DEFAULT NULL,
  `COLOR` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PERF_AGENDA`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene el catalogo de perfiles de Agenda';


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_rubro_inbound`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_rubro_inbound` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_rubro_inbound` (
  `ID_RUBRO_INBOUND` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_C_SISTEMA` INT(11) NULL DEFAULT NULL,
  `RUBRO_EVENTO` VARCHAR(30) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_RUBRO_INBOUND`),
  CONSTRAINT `FK_RELATIONSHIP_47`
    FOREIGN KEY (`ID_C_SISTEMA`)
    REFERENCES `BibliotecaDigital`.`c_sistema` (`ID_C_SISTEMA`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene el catalogo del Rubro de Evento';

CREATE INDEX `FK_RELATIONSHIP_47` ON `BibliotecaDigital`.`c_rubro_inbound` (`ID_C_SISTEMA` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_tipo_alarma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_tipo_alarma` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_tipo_alarma` (
  `id_tipo_alarma` INT(11) NOT NULL AUTO_INCREMENT,
  `alarma` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_alarma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_tipo_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_tipo_evento` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_tipo_evento` (
  `ID_TIPO_EVENTO` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_C_SISTEMA` INT(11) NULL DEFAULT NULL,
  `NOMBRE_EVENTO` VARCHAR(15) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL DEFAULT NULL,
  `ESTATUS` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_EVENTO`),
  CONSTRAINT `FK_RELATIONSHIP_33`
    FOREIGN KEY (`ID_C_SISTEMA`)
    REFERENCES `BibliotecaDigital`.`c_sistema` (`ID_C_SISTEMA`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_33` ON `BibliotecaDigital`.`c_tipo_evento` (`ID_C_SISTEMA` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`c_tipo_marcacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`c_tipo_marcacion` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`c_tipo_marcacion` (
  `ID_TIPO_MARC` INT(11) NOT NULL AUTO_INCREMENT,
  `TIPO_MARCACION` VARCHAR(15) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL DEFAULT NULL,
  `NUMERO_DIGITOS` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_MARC`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene el catalogo de tipos de Marcacion';


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`calendario` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`calendario` (
  `ID_CALENDARIO` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_CAMP` INT(11) NULL DEFAULT NULL,
  `year` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_CALENDARIO`),
  CONSTRAINT `FK_RELATIONSHIP_25`
    FOREIGN KEY (`ID_CAMP`)
    REFERENCES `BibliotecaDigital`.`campana` (`ID_CAMP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 173
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_25` ON `BibliotecaDigital`.`calendario` (`ID_CAMP` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`caller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`caller` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`caller` (
  `ID_CALLER` INT(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(20) NULL DEFAULT NULL,
  `A_PATERNO` VARCHAR(20) NULL DEFAULT NULL,
  `A_MATERNO` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CALLER`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla de registros de numeros telefonicos para marcacion de ';


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`campana_agente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`campana_agente` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`campana_agente` (
  `ID_USR` INT(11) NOT NULL,
  `ID_CAMP` INT(11) NOT NULL,
  `NIVEL_EXPERIENCIA` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_USR`, `ID_CAMP`),
  CONSTRAINT `FK_RELATIONSHIP_106`
    FOREIGN KEY (`ID_CAMP`)
    REFERENCES `BibliotecaDigital`.`campana` (`ID_CAMP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RELATIONSHIP_107`
    FOREIGN KEY (`ID_USR`)
    REFERENCES `BibliotecaDigital`.`usuario` (`ID_USR`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_106` ON `BibliotecaDigital`.`campana_agente` (`ID_CAMP` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`cat_ocupaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`cat_ocupaciones` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`cat_ocupaciones` (
  `id_ocupacion` INT(11) NOT NULL AUTO_INCREMENT,
  `desc_ocupacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ocupacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`cat_razonVisita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`cat_razonVisita` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`cat_razonVisita` (
  `id_razonVisita` INT(11) NOT NULL,
  `desc_razon` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_razonVisita`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`conexion_agente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`conexion_agente` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`conexion_agente` (
  `ID_ESTADO` INT(11) NOT NULL,
  `ID_ACT_PAUSA` INT(11) NULL DEFAULT NULL,
  `ID_USR` INT(11) NOT NULL,
  `FECHA_CONEXION` DATE NOT NULL,
  `HORA_CONEXION` TIME NOT NULL,
  `ESTADO_CONEXION` TINYINT(1) NOT NULL,
  `HORA_ESTADO` TIME NOT NULL,
  `ACUMULADO_PAUSA` TIME NOT NULL,
  `blaze_clientid` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_USR`),
  CONSTRAINT `FK_RELATIONSHIP_105`
    FOREIGN KEY (`ID_USR`)
    REFERENCES `BibliotecaDigital`.`usuario` (`ID_USR`),
  CONSTRAINT `FK_RELATIONSHIP_48`
    FOREIGN KEY (`ID_ESTADO`)
    REFERENCES `BibliotecaDigital`.`c_estado_agente` (`ID_ESTADO`),
  CONSTRAINT `FK_RELATIONSHIP_54`
    FOREIGN KEY (`ID_ACT_PAUSA`)
    REFERENCES `BibliotecaDigital`.`c_actividades_paus` (`ID_ACT_PAUSA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene la informacion de Conexion de un Agente a';

CREATE INDEX `FK_RELATIONSHIP_48` ON `BibliotecaDigital`.`conexion_agente` (`ID_ESTADO` ASC);

CREATE INDEX `FK_RELATIONSHIP_54` ON `BibliotecaDigital`.`conexion_agente` (`ID_ACT_PAUSA` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`configurador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`configurador` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`configurador` (
  `id_configurador` INT(11) NOT NULL,
  `ip_bd` VARCHAR(15) NULL DEFAULT NULL,
  `usuario_bd` VARCHAR(15) NULL DEFAULT NULL,
  `password_bd` VARCHAR(15) NULL DEFAULT NULL,
  `ip_envox` VARCHAR(15) NULL DEFAULT NULL,
  `crm` TINYINT(4) NOT NULL,
  `terminacion_llamada` TINYINT(4) NOT NULL,
  `marcacion_salida` TINYINT(4) NOT NULL,
  `prioridad_ag_calle` TINYINT(4) NOT NULL,
  `desborde` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_configurador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`dias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`dias` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`dias` (
  `ID_DIA` INT(11) NOT NULL AUTO_INCREMENT,
  `NOM_DIA` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_DIA`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`dias_especiales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`dias_especiales` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`dias_especiales` (
  `ID_DIA_ESPECIAL` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_CALENDARIO` INT(11) NOT NULL,
  `FECHA_DIA` DATE NULL DEFAULT NULL,
  `DESCRIPCION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_DIA_ESPECIAL`),
  CONSTRAINT `FK_RELATIONSHIP_26`
    FOREIGN KEY (`ID_CALENDARIO`)
    REFERENCES `BibliotecaDigital`.`calendario` (`ID_CALENDARIO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 173
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene los dias especiales del calendario';

CREATE INDEX `FK_RELATIONSHIP_26` ON `BibliotecaDigital`.`dias_especiales` (`ID_CALENDARIO` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`progreso_eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`progreso_eventos` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`progreso_eventos` (
  `ID_PROGRESO_EVENTO` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(100) NULL DEFAULT NULL,
  `PROGRESO_EVENTO` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID_PROGRESO_EVENTO`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene el catalogo de Progresos de un Evento';


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`evento` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`evento` (
  `ID_EVENTO` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_CALLER` INT(11) NULL DEFAULT NULL,
  `ID_TIPO_EVENTO` INT(11) NULL DEFAULT NULL,
  `ID_TIPO_MARC` INT(11) NULL DEFAULT NULL,
  `ID_PROGRESO_EVENTO` INT(11) NULL DEFAULT NULL,
  `ID_USR` INT(11) NULL DEFAULT NULL,
  `FECH_ATENCION` DATE NULL DEFAULT NULL,
  `HORA_ATENCION` TIME NULL DEFAULT NULL,
  `FECH_FIN_LLAMADA` DATE NULL DEFAULT NULL,
  `HORA_FIN_LLAMADA` TIME NULL DEFAULT NULL,
  `FECH_POST_LLAMADA` DATE NULL DEFAULT NULL,
  `HORA_POST_LLAMADA` TIME NULL DEFAULT NULL,
  `PUERTO` INT(11) NULL DEFAULT NULL,
  `NUM_TELEFONO` VARCHAR(15) NULL DEFAULT NULL,
  `FECHA_INICIO_LLAMADA` DATE NULL DEFAULT NULL,
  `HORA_INICIO_LLAMADA` TIME NULL DEFAULT NULL,
  `FECHA_TRANS` DATE NULL DEFAULT NULL,
  `HORA_TRANS` TIME NULL DEFAULT NULL,
  `ID_CAMP` INT(11) NULL DEFAULT NULL,
  `FOLIO_EVENTO` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_EVENTO`),
  CONSTRAINT `FK_RELATIONSHIP_108`
    FOREIGN KEY (`ID_USR`)
    REFERENCES `BibliotecaDigital`.`usuario` (`ID_USR`),
  CONSTRAINT `FK_RELATIONSHIP_28`
    FOREIGN KEY (`ID_CALLER`)
    REFERENCES `BibliotecaDigital`.`caller` (`ID_CALLER`),
  CONSTRAINT `FK_RELATIONSHIP_32`
    FOREIGN KEY (`ID_TIPO_EVENTO`)
    REFERENCES `BibliotecaDigital`.`c_tipo_evento` (`ID_TIPO_EVENTO`),
  CONSTRAINT `FK_RELATIONSHIP_38`
    FOREIGN KEY (`ID_TIPO_MARC`)
    REFERENCES `BibliotecaDigital`.`c_tipo_marcacion` (`ID_TIPO_MARC`),
  CONSTRAINT `FK_RELATIONSHIP_40`
    FOREIGN KEY (`ID_PROGRESO_EVENTO`)
    REFERENCES `BibliotecaDigital`.`progreso_eventos` (`ID_PROGRESO_EVENTO`),
  CONSTRAINT `FK_RELATIONSHIP_66`
    FOREIGN KEY (`ID_CAMP`)
    REFERENCES `BibliotecaDigital`.`campana` (`ID_CAMP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla de Evento';

CREATE INDEX `FK_RELATIONSHIP_108` ON `BibliotecaDigital`.`evento` (`ID_USR` ASC);

CREATE INDEX `FK_RELATIONSHIP_28` ON `BibliotecaDigital`.`evento` (`ID_CALLER` ASC);

CREATE INDEX `FK_RELATIONSHIP_32` ON `BibliotecaDigital`.`evento` (`ID_TIPO_EVENTO` ASC);

CREATE INDEX `FK_RELATIONSHIP_38` ON `BibliotecaDigital`.`evento` (`ID_TIPO_MARC` ASC);

CREATE INDEX `FK_RELATIONSHIP_40` ON `BibliotecaDigital`.`evento` (`ID_PROGRESO_EVENTO` ASC);

CREATE INDEX `FK_RELATIONSHIP_66` ON `BibliotecaDigital`.`evento` (`ID_CAMP` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`evento_inbound`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`evento_inbound` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`evento_inbound` (
  `ID_EVENTO_INBOUND` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_EVENTO` INT(11) UNSIGNED NOT NULL,
  `ID_RES_IN` INT(11) NULL DEFAULT NULL,
  `ID_RUBRO_INBOUND` INT(11) NULL DEFAULT NULL,
  `ID_GPO_ATN_IN` INT(11) NULL DEFAULT NULL,
  `NUM_CICLOS` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_EVENTO_INBOUND`),
  CONSTRAINT `FK_RELATIONSHIP_30`
    FOREIGN KEY (`ID_EVENTO`)
    REFERENCES `BibliotecaDigital`.`evento` (`ID_EVENTO`),
  CONSTRAINT `FK_RELATIONSHIP_51`
    FOREIGN KEY (`ID_RES_IN`)
    REFERENCES `BibliotecaDigital`.`c_resultados_inbou` (`ID_RES_IN`),
  CONSTRAINT `FK_RELATIONSHIP_52`
    FOREIGN KEY (`ID_GPO_ATN_IN`)
    REFERENCES `BibliotecaDigital`.`c_gpo_atn_inbound` (`ID_GPO_ATN_IN`),
  CONSTRAINT `FK_RELATIONSHIP_53`
    FOREIGN KEY (`ID_RUBRO_INBOUND`)
    REFERENCES `BibliotecaDigital`.`c_rubro_inbound` (`ID_RUBRO_INBOUND`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene los atributos de un evento Inbound';

CREATE INDEX `FK_RELATIONSHIP_30` ON `BibliotecaDigital`.`evento_inbound` (`ID_EVENTO` ASC);

CREATE INDEX `FK_RELATIONSHIP_51` ON `BibliotecaDigital`.`evento_inbound` (`ID_RES_IN` ASC);

CREATE INDEX `FK_RELATIONSHIP_52` ON `BibliotecaDigital`.`evento_inbound` (`ID_GPO_ATN_IN` ASC);

CREATE INDEX `FK_RELATIONSHIP_53` ON `BibliotecaDigital`.`evento_inbound` (`ID_RUBRO_INBOUND` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`evento_outbound`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`evento_outbound` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`evento_outbound` (
  `ID_EVENTO_OUTBOUND` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_EVENTO` INT(11) UNSIGNED NOT NULL,
  `ID_RES_OUT` INT(11) NULL DEFAULT NULL,
  `NUM_INTENTOS` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_EVENTO_OUTBOUND`),
  CONSTRAINT `FK_RELATIONSHIP_31`
    FOREIGN KEY (`ID_EVENTO`)
    REFERENCES `BibliotecaDigital`.`evento` (`ID_EVENTO`),
  CONSTRAINT `FK_RELATIONSHIP_50`
    FOREIGN KEY (`ID_RES_OUT`)
    REFERENCES `BibliotecaDigital`.`c_resultados_outbo` (`ID_RES_OUT`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_31` ON `BibliotecaDigital`.`evento_outbound` (`ID_EVENTO` ASC);

CREATE INDEX `FK_RELATIONSHIP_50` ON `BibliotecaDigital`.`evento_outbound` (`ID_RES_OUT` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`historico_alarmas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`historico_alarmas` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`historico_alarmas` (
  `id_historico_alarma` INT(11) NOT NULL,
  `id_camp` INT(11) NOT NULL,
  `id_tipo_alarma` INT(11) NOT NULL,
  `fecha_alarma` DATE NOT NULL,
  `hora_alarma` TIME NOT NULL,
  `descripcion_alarma` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_historico_alarma`),
  CONSTRAINT `FK_RELATIONSHIP_AL`
    FOREIGN KEY (`id_tipo_alarma`)
    REFERENCES `BibliotecaDigital`.`c_tipo_alarma` (`id_tipo_alarma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RELATIONSHIP_CAMP`
    FOREIGN KEY (`id_camp`)
    REFERENCES `BibliotecaDigital`.`campana` (`ID_CAMP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_AL` ON `BibliotecaDigital`.`historico_alarmas` (`id_tipo_alarma` ASC);

CREATE INDEX `FK_RELATIONSHIP_CAMP` ON `BibliotecaDigital`.`historico_alarmas` (`id_camp` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`horas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`horas` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`horas` (
  `ID_HORA` INT(11) NOT NULL AUTO_INCREMENT,
  `HORA` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_HORA`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`mapa_call`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`mapa_call` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`mapa_call` (
  `ID_MAPA` INT(11) NOT NULL AUTO_INCREMENT,
  `NUM_FILAS` INT(11) NULL DEFAULT NULL,
  `NUM_COLUMNAS` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_MAPA`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que contiene el tamaño real de la vista aerea del Call';


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`menus` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`menus` (
  `idmenu` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` INT(11) NULL DEFAULT NULL,
  `idpadre` VARCHAR(45) NULL DEFAULT NULL,
  `forma` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmenu`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`posiciones_call`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`posiciones_call` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`posiciones_call` (
  `ID_POSICION` INT(11) NOT NULL AUTO_INCREMENT,
  `COORDENADA_POS` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_POSICION`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabla que guarda registros de posiciones de los agentes dent';


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`seg_registroVisitante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`seg_registroVisitante` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`seg_registroVisitante` (
  `id_registroVisitante` INT(11) NOT NULL AUTO_INCREMENT,
  `genero` CHAR(1) NULL DEFAULT NULL,
  `edad` INT(11) NULL DEFAULT NULL,
  `id_ocupacion` INT(11) NULL DEFAULT NULL,
  `estado_civil` VARCHAR(45) NULL DEFAULT NULL,
  `id_razonVisita` INT(11) NULL DEFAULT NULL,
  `frecuencia` INT(11) NULL DEFAULT NULL,
  `num_acompanantes` INT(11) NULL DEFAULT NULL,
  `fecha_visita` DATE NULL DEFAULT NULL,
  `hora_visita` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_registroVisitante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`supervisor_agente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`supervisor_agente` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`supervisor_agente` (
  `ID_SUPERVISOR_AGENTE` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_AGENTE` INT(11) NULL DEFAULT NULL,
  `ID_SUPERVISOR` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_SUPERVISOR_AGENTE`),
  CONSTRAINT `FK_RELATIONSHIP_109`
    FOREIGN KEY (`ID_AGENTE`)
    REFERENCES `BibliotecaDigital`.`usuario` (`ID_USR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_109` ON `BibliotecaDigital`.`supervisor_agente` (`ID_AGENTE` ASC);


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`telefono_caller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`telefono_caller` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`telefono_caller` (
  `ID_CALLER` INT(11) NOT NULL,
  `TELEFONO_CALLER` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`ID_CALLER`),
  CONSTRAINT `FK_RELATIONSHIP_29`
    FOREIGN KEY (`ID_CALLER`)
    REFERENCES `BibliotecaDigital`.`caller` (`ID_CALLER`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `BibliotecaDigital`.`voces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BibliotecaDigital`.`voces` ;

CREATE TABLE IF NOT EXISTS `BibliotecaDigital`.`voces` (
  `ID_VOCES` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_CAMP` INT(11) NOT NULL,
  `BVN_HRO_LABORAL` VARCHAR(150) NOT NULL,
  `BVN_FIN_SEMANA` VARCHAR(150) NOT NULL,
  `BVN_HRO_ESPECIAL` VARCHAR(150) NOT NULL,
  `BVN_HRO_CERRADO` VARCHAR(150) NOT NULL,
  `BVN_BUZON_DIURNO` VARCHAR(150) NOT NULL,
  `BVN_BUZON_NOCTURNO` VARCHAR(150) NOT NULL,
  `TRANSFERENCIA` VARCHAR(150) NOT NULL,
  `OPCION_INVALIDA` VARCHAR(150) NOT NULL,
  `DESPEDIDA` VARCHAR(150) NOT NULL,
  `AGENTES_NO_DISP` VARCHAR(150) NOT NULL,
  `IND_MUSICA1` VARCHAR(150) NOT NULL,
  `IND_MUSICA2` VARCHAR(150) NULL DEFAULT NULL,
  `IND_MUSICA3` VARCHAR(150) NULL DEFAULT NULL,
  `ESPERA1` VARCHAR(150) NOT NULL,
  `ESPERA2` VARCHAR(150) NULL DEFAULT NULL,
  `ESPERA3` VARCHAR(150) NULL DEFAULT NULL,
  `MENSAJE` VARCHAR(150) NOT NULL,
  `DISUASION` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID_VOCES`),
  CONSTRAINT `FK_RELATIONSHIP_7`
    FOREIGN KEY (`ID_CAMP`)
    REFERENCES `BibliotecaDigital`.`campana` (`ID_CAMP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_RELATIONSHIP_7` ON `BibliotecaDigital`.`voces` (`ID_CAMP` ASC);

USE `BibliotecaDigital` ;

-- -----------------------------------------------------
-- function creaMenuDB
-- -----------------------------------------------------

USE `BibliotecaDigital`;
DROP function IF EXISTS `BibliotecaDigital`.`creaMenuDB`;

DELIMITER $$
USE `BibliotecaDigital`$$
CREATE DEFINER=`root`@`%` FUNCTION `creaMenuDB`(id_usuario INT) RETURNS varchar(65000) CHARSET latin1
BEGIN    
   DECLARE record_not_found     INTEGER DEFAULT 0;
   DECLARE descripcion0         VARCHAR(100) DEFAULT "";
   DECLARE descripcionhijo      VARCHAR(100) DEFAULT "";
   DECLARE descripcionnieto     VARCHAR(100) DEFAULT "";
   
   DECLARE forma0               VARCHAR(100) DEFAULT "";
   DECLARE formahijo            VARCHAR(100) DEFAULT "";	
   DECLARE formanieto           VARCHAR(100) DEFAULT "";
   
   DECLARE menu                 VARCHAR(65000) DEFAULT ""; 
   DECLARE idmenucur            INT DEFAULT 0;
   DECLARE idmenucurhijo        INT DEFAULT 0;
   DECLARE idmenucurnieto       INT DEFAULT 0; 
   DECLARE tipomenu             INT DEFAULT 0;
   DECLARE tipomenunieto        INT DEFAULT 0;
   DECLARE id_tipo_usuario      INT DEFAULT 0;
   DECLARE bandera_padre        INT DEFAULT 0;
   DECLARE bandera_hijo         INT DEFAULT 0;
   
   DECLARE my_cursor     CURSOR FOR SELECT descripcion, forma, idmenu FROM menus WHERE idpadre = 0 ORDER BY descripcion;
   DECLARE cur_hijos     CURSOR FOR SELECT descripcion, forma, idmenu, tipo FROM menus WHERE idpadre = idmenucur ORDER BY descripcion;
   DECLARE cur_nietos    CURSOR FOR SELECT descripcion, forma, idmenu, tipo  FROM menus WHERE idpadre = idmenucurhijo ORDER BY descripcion;
   
   
   DECLARE CONTINUE HANDLER FOR NOT FOUND SET record_not_found = 1;
   
   SELECT id_tipo_usr INTO id_tipo_usuario FROM usuario WHERE id_usr = id_usuario;

   SET menu="<menus>";
   
   OPEN my_cursor;    
   
   ciclo_padre: LOOP 
   FETCH my_cursor INTO descripcion0, forma0, idmenucur; 
   IF record_not_found THEN
		CLOSE my_cursor;
		LEAVE ciclo_padre; 
   END IF; 

	CASE id_tipo_usuario
		WHEN 1 THEN	
			IF LCASE(descripcion0) = "administración" OR LCASE(descripcion0) = "supervisión" OR LCASE(descripcion0) = "reportes" THEN
				IF forma0 IS NULL THEN
					SET menu= CONCAT(menu,"<menu0 label=",'"',descripcion0,'"'," forma=",'""'," >");
				ELSE
					SET menu= CONCAT(menu,"<menu0 label=",'"',descripcion0,'"'," forma=",'"',forma0,'"'," >");
				END IF;
                SET bandera_padre = 1;
            ELSE
                SET bandera_padre = 0;
			END IF;
		WHEN 2 THEN 
			IF LCASE(descripcion0) = "administración" OR LCASE(descripcion0) = "supervisión" OR LCASE(descripcion0) = "atención" THEN
				IF forma0 IS NULL THEN
					SET menu= CONCAT(menu,"<menu0 label=",'"',descripcion0,'"'," forma=",'""'," >");
				ELSE
					SET menu= CONCAT(menu,"<menu0 label=",'"',descripcion0,'"'," forma=",'"',forma0,'"'," >");
				END IF;
				SET bandera_padre = 1;
            ELSE
                SET bandera_padre = 0;
			END IF;
		WHEN 3 THEN 
			IF LCASE(descripcion0) = "administración" OR LCASE(descripcion0) = "supervisión" OR LCASE(descripcion0) = "reportes" THEN
				IF forma0 IS NULL THEN
					SET menu= CONCAT(menu,"<menu0 label=",'"',descripcion0,'"'," forma=",'""'," >");
				ELSE
					SET menu= CONCAT(menu,"<menu0 label=",'"',descripcion0,'"'," forma=",'"',forma0,'"'," >");
				END IF;
				SET bandera_padre = 1;
            ELSE
                SET bandera_padre = 0;
			END IF;
		WHEN 4 THEN 
			IF LCASE(descripcion0) = "administración" THEN
				IF forma0 IS NULL THEN
					SET menu= CONCAT(menu,"<menu0 label=",'"',descripcion0,'"'," forma=",'""'," >");
				ELSE
					SET menu= CONCAT(menu,"<menu0 label=",'"',descripcion0,'"'," forma=",'"',forma0,'"'," >");
				END IF;
                SET bandera_padre = 1;
			ELSE
                SET bandera_padre = 0;
			END IF;
	END CASE;
	OPEN cur_hijos;
        ciclo_hijos: LOOP
         FETCH cur_hijos INTO descripcionhijo, formahijo, idmenucurhijo, tipomenu;
            IF record_not_found THEN 
                CLOSE cur_hijos;
                SET record_not_found = 0;
                LEAVE ciclo_hijos;
            END IF;
            IF tipomenu = 1 THEN
				CASE id_tipo_usuario
					WHEN 1 THEN	
						IF LCASE(descripcionhijo) = "catálogos" OR LCASE(descripcionhijo) = "nivel de servicio" OR LCASE(descripcionhijo) = "Productividad" OR
						   LCASE(descripcionhijo) = "tráfico de llamadas" OR LCASE(descripcionhijo) = "utilización" THEN
							IF formahijo IS NULL THEN
								SET menu= CONCAT(menu,"<menu1 label=",'"',descripcionhijo,'"'," forma=",'""'," >");
							ELSE
								SET menu= CONCAT(menu,"<menu1 label=",'"',descripcionhijo,'"'," forma=",'"',formahijo,'"'," >");
							END IF;
							set bandera_hijo = 1;
						else
							set bandera_hijo = 0;
						END IF;
					WHEN 2 THEN	
						SET menu= CONCAT(menu,"");
						SET bandera_hijo = 0;
					WHEN 3 THEN 
						IF LCASE(descripcionhijo) = "catálogos" OR LCASE(descripcionhijo) = "nivel de servicio" OR LCASE(descripcionhijo) = "Productividad" OR
						   LCASE(descripcionhijo) = "tráfico de llamadas" OR LCASE(descripcionhijo) = "utilización" THEN
							IF formahijo IS NULL THEN
								SET menu= CONCAT(menu,"<menu1 label=",'"',descripcionhijo,'"'," forma=",'""'," >");
							ELSE
								SET menu= CONCAT(menu,"<menu1 label=",'"',descripcionhijo,'"'," forma=",'"',formahijo,'"'," >");
							END IF;
							set bandera_hijo = 1;
						else
							set bandera_hijo = 0;
						END IF;
					WHEN 4 THEN 
						SET menu= CONCAT(menu,"");
						SET bandera_hijo = 0;
				END CASE;
            OPEN cur_nietos;
                ciclo_nietos: LOOP
                FETCH cur_nietos INTO descripcionnieto, formanieto, idmenucurnieto, tipomenunieto ;
                IF record_not_found THEN 
                CLOSE cur_nietos;
                SET record_not_found = 0;
                LEAVE ciclo_nietos;
                END IF;
                IF tipomenunieto = 1 THEN
				   
				   
				   SET menu= CONCAT(menu,"");
					
					
					
					
					
					
					
					
					
					
					
                
				
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                ELSE 
					CASE id_tipo_usuario
						WHEN 1 THEN	
							IF LCASE(descripcionnieto) = "resultados inbound" OR LCASE(descripcionnieto) = "resultados outbound" OR LCASE(descripcionnieto) = "integración crm" OR 
							   LCASE(descripcionnieto) = "tiempos generales de nivel de servicio" OR LCASE(descripcionnieto) = "operación diaria" OR 
							   LCASE(descripcionnieto) = "atención de eventos" OR LCASE(descripcionnieto) = "duración de servicio" OR LCASE(descripcionnieto) = "tráfico de llamadas" OR
							   LCASE(descripcionnieto) = "destino de llamadas" OR LCASE(descripcionnieto) = "nivel de atención por fecha" OR LCASE(descripcionnieto) = "nivel de atención por hora" THEN
								IF formanieto IS NULL THEN
									SET menu= CONCAT(menu,"<menuitem label=",'"',descripcionnieto,'"'," forma=",'""'," />");
								ELSE
									SET menu= CONCAT(menu,"<menuitem label=",'"',descripcionnieto,'"'," forma=",'"',formanieto,'"'," />");
								END IF;
							END IF;
						WHEN 2 THEN	
							SET menu= CONCAT(menu,"");
						WHEN 3 THEN 
							IF LCASE(descripcionnieto) = "resultados inbound" OR LCASE(descripcionnieto) = "resultados outbound" OR LCASE(descripcionnieto) = "integración crm" OR 
							   LCASE(descripcionnieto) = "tiempos generales de nivel de servicio" OR LCASE(descripcionnieto) = "operación diaria" OR 
							   LCASE(descripcionnieto) = "atención de eventos" OR LCASE(descripcionnieto) = "duración de servicio" OR LCASE(descripcionnieto) = "tráfico de llamadas" OR
							   LCASE(descripcionnieto) = "destino de llamadas" OR LCASE(descripcionnieto) = "nivel de atención por fecha" OR LCASE(descripcionnieto) = "nivel de atención por hora" THEN
								IF formanieto IS NULL THEN
									SET menu= CONCAT(menu,"<menuitem label=",'"',descripcionnieto,'"'," forma=",'""'," />");
								ELSE
									SET menu= CONCAT(menu,"<menuitem label=",'"',descripcionnieto,'"'," forma=",'"',formanieto,'"'," />");
								END IF;
							END IF;
						WHEN 4 THEN 
							SET menu= CONCAT(menu,"");
					END CASE;
                END IF;
                END LOOP ciclo_nietos;
				IF bandera_hijo = 1 THEN
                    SET menu = CONCAT(menu,"</menu1>");
				END IF;
            ELSE 
				CASE id_tipo_usuario
					WHEN 1 THEN	
						IF LCASE(descripcionhijo) != "configurar sistema" AND LCASE(descripcionhijo) != "atender eventos" THEN
							IF formahijo IS NULL THEN
								SET menu= CONCAT(menu,"<menuitem label=",'"',descripcionhijo,'"'," forma=",'""',"/>");
							ELSE
								SET menu= CONCAT(menu,"<menuitem label=",'"',descripcionhijo,'"'," forma=",'"',formahijo,'"',"/>");
							END IF;
						END IF;
					WHEN 2 THEN	
						IF LCASE(descripcionhijo) = "cambiar contraseña"  OR LCASE(descripcionhijo) = "enviar mensaje" OR LCASE(descripcionhijo) = "atender eventos" THEN
							IF formahijo IS NULL THEN
								SET menu= CONCAT(menu,"<menuitem label=",'"',descripcionhijo,'"'," forma=",'""',"/>");
							ELSE
								SET menu= CONCAT(menu,"<menuitem label=",'"',descripcionhijo,'"'," forma=",'"',formahijo,'"',"/>");
							END IF;
						END IF;
					WHEN 3 THEN 
						IF LCASE(descripcionhijo) != "configurar sistema" AND LCASE(descripcionhijo) != "atender eventos" THEN
							IF formahijo IS NULL THEN
								SET menu= CONCAT(menu,"<menuitem label=",'"',descripcionhijo,'"'," forma=",'""',"/>");
							ELSE
								SET menu= CONCAT(menu,"<menuitem label=",'"',descripcionhijo,'"'," forma=",'"',formahijo,'"',"/>");
							END IF;
						END IF;
					WHEN 4 THEN 
						IF LCASE(descripcionhijo) = "cambiar contraseña"  OR LCASE(descripcionhijo) = "configurar sistema" THEN
							IF formahijo IS NULL THEN
								SET menu= CONCAT(menu,"<menuitem label=",'"',descripcionhijo,'"'," forma=",'""',"/>");
							ELSE
								SET menu= CONCAT(menu,"<menuitem label=",'"',descripcionhijo,'"'," forma=",'"',formahijo,'"',"/>");
							END IF;
						END IF;
				END CASE;
            END IF; 
         END LOOP ciclo_hijos;
		IF bandera_padre = 1 THEN
		SET menu = CONCAT(menu,"</menu0>");
    END IF;
   END LOOP ciclo_padre;    
   SET menu = CONCAT(menu,"</menus>");    
   RETURN menu; 
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
